### ISSUE TITLE
default nginx page after fresh install

### ISSUE THREAD

**Issue by isAAAc** [aymhce/diaspora_ynh#13]
Hi, 
i just went to install diaspora on a VPS, but the url gives me the default nginx page instead of diaspora : 
```
Welcome to nginx on Debian!

If you see this page, the nginx web server is successfully installed and working on Debian. Further configuration is required.

For online documentation and support please refer to nginx.org

Please use the reportbug tool to report bugs in the nginx package with Debian. However, check existing bug reports before reporting a new bug.

Thank you for using debian and nginx.
```

Could someone explain me howto do to fix this please ?

service diaspora_ynh status
```
● diaspora_ynh.service - LSB: Diaspora application server
   Loaded: loaded (/etc/init.d/diaspora_ynh)
   Active: active (exited) since ven. 2018-06-15 10:15:54 CEST; 52min ago

juin 15 10:15:54 krashboyz diaspora_ynh[13253]: touch: impossible de faire un touch « /var/www/diaspora/log/startscript.log »: Aucun fichier ou dossier de ce type
juin 15 10:15:54 krashboyz diaspora_ynh[13253]: Could not touch logfile ... failed!
juin 15 10:15:54 krashboyz systemd[1]: Started LSB: Diaspora application server.
```

yunohost -v
```
yunohost:
  repo: stable
  version: 2.7.12
yunohost-admin:
  repo: stable
  version: 2.7.12
moulinette:
  repo: stable
  version: 2.7.12
ssowat:
  repo: stable
  version: 2.7.12

```
